name: Debian Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: telegram-cli
        path: dist/*.deb
